name: TestPipelineAction action
on:
  push:

jobs:
  Test_Partitation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls -a
          npm install
          npm start

