name: TestPipelineAction action
on:
  push:

jobs:
  Test_Partitation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'refs/heads/*'
          fetch-depth: 0
      - run: |
          ls -a
          npm install
          npm start

